// src/components/employees/PostEmployee.jsx

import { useState } from "react";
import { X, User, Lock, Building2, Briefcase, Eye, EyeOff, Hash } from "lucide-react";

// STATIC PLACEHOLDER DATA — using hardcoded values until the backend endpoints below exist.
//
// @backend, please provide:
//   GET /api/departments
//     -> 200: [{ id: string, name: string }, ...]
//
//   GET /api/positions?departmentId={id}
//     -> 200: [{ id: string, name: string, departmentId: string }, ...]
//     (Position list should be filterable by department, since the form
//     will re-request/re-filter positions whenever the department changes.)
const DEPARTMENTS = ["IT", "HR", "Finance", "Marketing"];
const POSITIONS = [
  "Software Engineer",
  "HR Officer",
  "Accountant",
  "Marketing Specialist",
  "Manager",
  "Intern",
];

const PostEmployee = ({ isOpen, onClose, onSubmit }) => {
  const [showPassword, setShowPassword] = useState(false);
  const [form, setForm] = useState({
    employeeId: "",
    name: "",
    password: "",
    department: "",
    position: "",
  });

  // @backend: please confirm how Employee ID should work —
  //   (a) auto-generated by the backend on creation (frontend wouldn't send it,
  //       and this field would instead be removed or shown as read-only "Auto-generated"), or
  //   (b) entered manually here and sent as part of the POST body, in which case
  //       please confirm the expected format (e.g. "EMP-0001") and whether it must be unique.
  // Currently built as a manual text input (option b) until this is confirmed.

  // The frontend will track isSubmitting/submitError locally once the create-employee
  // endpoint exists — no action needed from backend here, just noting the dependency:
  //   const [isSubmitting, setIsSubmitting] = useState(false);
  //   const [submitError, setSubmitError] = useState(null);

  if (!isOpen) return null;

  const handleChange = (field) => (e) => {
    setForm((prev) => ({ ...prev, [field]: e.target.value }));
  };

  // onSubmit?.(form) below currently just hands the raw form values up to the parent.
  // Once wired to a real API, the frontend will call:
  //
  //   POST /api/employees
  //   Request body:  { employeeId: string, name: string, password: string, department: string, position: string }
  //   (employeeId is omitted from the body if the backend decides to auto-generate it instead — see note above)
  //
  // @backend, please confirm/provide:
  //   - Success response shape, e.g. 201: { id, name, department, position, createdAt }
  //     (no password or password hash should ever be included in the response)
  //   - Validation errors as 400 with a field-level shape, e.g.
  //       { errors: { name: "Name is required", password: "Too short" } }
  //     so the frontend can show them next to the right input.
  //   - Conflict case (duplicate employee name / account) as 409 with a message field.
  //   - The password must be hashed (e.g. bcrypt) server-side before storage —
  //     the frontend only ever sends it once, over HTTPS, and never stores it.
  const handleSubmit = (e) => {
    e.preventDefault();
    onSubmit?.(form);
    setForm({ employeeId: "", name: "", password: "", department: "", position: "" });
    onClose?.();
  };

  const handleClose = () => {
    setForm({ employeeId: "", name: "", password: "", department: "", position: "" });
    onClose?.();
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/50 backdrop-blur-sm"
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) handleClose();
      }}
    >
      <div className="w-full max-w-md bg-white rounded-2xl shadow-xl border overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-5 border-b bg-gradient-to-r from-blue-600 to-blue-700">
          <div>
            <h2 className="text-lg font-semibold text-white">Add Employee</h2>
            <p className="text-blue-100 text-sm">
              Create a new employee account.
            </p>
          </div>
          <button
            onClick={handleClose}
            className="text-blue-100 hover:text-white hover:bg-white/10 rounded-lg p-1.5 transition"
            aria-label="Close"
          >
            <X size={20} />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="px-6 py-6 space-y-5">
          {/* Employee Name */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Employee Name
            </label>
            <div className="relative">
              <User
                size={18}
                className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"
              />
              <input
                type="text"
                value={form.name}
                onChange={handleChange("name")}
                placeholder="e.g. Sarah Mitchell"
                className="w-full border border-gray-300 rounded-lg pl-10 pr-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>

          {/* Employee ID */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Employee ID
            </label>
            <div className="relative">
              <Hash
                size={18}
                className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"
              />
              <input
                type="text"
                value={form.employeeId}
                onChange={handleChange("employeeId")}
                placeholder="e.g. EMP-0001"
                className="w-full border border-gray-300 rounded-lg pl-10 pr-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>

          {/* Password */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Password
            </label>
            <div className="relative">
              <Lock
                size={18}
                className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"
              />
              <input
                type={showPassword ? "text" : "password"}
                value={form.password}
                onChange={handleChange("password")}
                placeholder="Minimum 6 characters"
                className="w-full border border-gray-300 rounded-lg pl-10 pr-10 py-2.5 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              <button
                type="button"
                onClick={() => setShowPassword((prev) => !prev)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                aria-label={showPassword ? "Hide password" : "Show password"}
              >
                {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>
          </div>

          {/* Department & Position */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">
                Department
              </label>
              <div className="relative">
                <Building2
                  size={18}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"
                />
                <select
                  value={form.department}
                  onChange={handleChange("department")}
                  className="w-full appearance-none border border-gray-300 rounded-lg pl-10 pr-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select</option>
                  {/* @backend: replace this static list once GET /api/departments is available */}
                  {DEPARTMENTS.map((dept) => (
                    <option key={dept} value={dept}>
                      {dept}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">
                Position
              </label>
              <div className="relative">
                <Briefcase
                  size={18}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"
                />
                <select
                  value={form.position}
                  onChange={handleChange("position")}
                  className="w-full appearance-none border border-gray-300 rounded-lg pl-10 pr-4 py-2.5 focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select</option>
                  {/* @backend: replace this static list once GET /api/positions?departmentId={id} is available */}
                  {POSITIONS.map((pos) => (
                    <option key={pos} value={pos}>
                      {pos}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          {/* Will render submitError here once the create-employee endpoint is live, e.g.
              {submitError && <p className="text-red-500 text-sm">{submitError}</p>} */}

          {/* Actions */}
          <div className="flex items-center justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={handleClose}
              className="px-5 py-2.5 rounded-lg border text-gray-600 hover:bg-gray-50 transition"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-5 py-2.5 rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition shadow-sm"
              // will add disabled={isSubmitting} once the endpoint above exists
            >
              {/* will show "Adding..." while isSubmitting is true */}
              Add Employee
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default PostEmployee;
